/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'lore-articles': LoreArticle;
    groups: Group;
    ships: Ship;
    weapons: Weapon;
    armors: Armor;
    characters: Character;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'lore-articles': LoreArticlesSelect<false> | LoreArticlesSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    ships: ShipsSelect<false> | ShipsSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    armors: ArmorsSelect<false> | ArmorsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Détermine les droits de l'utilisateur dans l'application.
   */
  role: 'admin' | 'player';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles encyclopédiques de l'univers Space Squad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lore-articles".
 */
export interface LoreArticle {
  id: number;
  title: string;
  /**
   * Généré automatiquement depuis le titre. Modifiable manuellement si besoin.
   */
  slug?: string | null;
  category: 'chronologies' | 'especes-non-humaines' | 'politique' | 'technologie' | 'culture' | 'stardash';
  /**
   * Courte description affichée dans les listes et aperçus (facultatif).
   */
  excerpt?: string | null;
  /**
   * Image d'en-tête de l'article (facultatif).
   */
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  nom: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ships".
 */
export interface Ship {
  id: number;
  nom: string;
  classe?: ('alpha' | 'beta' | 'gamma' | 'delta') | null;
  modele?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: number;
  nom: string;
  /**
   * Poids de l'arme (en kg)
   */
  poids?: number | null;
  tailleChargeur?: number | null;
  valeurDegats?: number | null;
  projectilesParTir?: number | null;
  valeurRechargement?: number | null;
  /**
   * Modification(s) installée(s) sur cette arme.
   */
  mods?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armors".
 */
export interface Armor {
  id: number;
  nom: string;
  valeurArmurePhysique?: number | null;
  valeurBouclier?: number | null;
  /**
   * Modificateur appliqué aux jets (positif ou négatif).
   */
  modificateur?: number | null;
  valeurRupture?: number | null;
  /**
   * Modification(s) installée(s) sur cette pièce d'armure.
   */
  mods?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  /**
   * Utilisateur propriétaire de ce personnage (1 personnage par compte).
   */
  user: number | User;
  nom?: string | null;
  sexe?: ('M' | 'F' | 'X') | null;
  origine?: ('Humain' | 'Strani' | 'Vada') | null;
  affiliation?: ('Alliance' | 'Union' | 'Guilde') | null;
  groupe?: (number | null) | Group;
  pointsDeRang?: number | null;
  konis?: number | null;
  legende?: number | null;
  force?: number | null;
  habilite?: number | null;
  connaissances?: number | null;
  culture?: number | null;
  anticipation?: number | null;
  perception?: number | null;
  armureTete?: (number | null) | Armor;
  armureTorse?: (number | null) | Armor;
  armureBras?: (number | null) | Armor;
  armureJambes?: (number | null) | Armor;
  armePrincipale?: (number | null) | Weapon;
  armeSecondaire?: (number | null) | Weapon;
  armeLourde?: (number | null) | Weapon;
  armeDePoing?: (number | null) | Weapon;
  armeDeMelee?: (number | null) | Weapon;
  backpack?: string | null;
  vaisseau?: (number | null) | Ship;
  roleVaisseau?: ('proprietaire' | 'passager') | null;
  /**
   * Compétences de la liste standard et leur niveau.
   */
  competences?:
    | {
        competence:
          | 'Chasseur'
          | 'Bombardier'
          | 'Poids Lourds'
          | 'Transport de Troupes'
          | 'Canonnier'
          | 'Médecine de terrain'
          | 'Concentration'
          | 'Mécanicien'
          | 'Stabilisation'
          | 'Assaut'
          | 'Sniper'
          | 'Shotgun'
          | 'Combat rapproché'
          | 'Analyse'
          | 'Réactivité'
          | 'Furtivité'
          | 'Diplomate'
          | 'Culture';
        valeur: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Compétences uniques, hors liste standard, propres à ce personnage.
   */
  competencesSpeciales?:
    | {
        nom: string;
        valeur: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'lore-articles';
        value: number | LoreArticle;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'ships';
        value: number | Ship;
      } | null)
    | ({
        relationTo: 'weapons';
        value: number | Weapon;
      } | null)
    | ({
        relationTo: 'armors';
        value: number | Armor;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lore-articles_select".
 */
export interface LoreArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  nom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ships_select".
 */
export interface ShipsSelect<T extends boolean = true> {
  nom?: T;
  classe?: T;
  modele?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  nom?: T;
  poids?: T;
  tailleChargeur?: T;
  valeurDegats?: T;
  projectilesParTir?: T;
  valeurRechargement?: T;
  mods?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armors_select".
 */
export interface ArmorsSelect<T extends boolean = true> {
  nom?: T;
  valeurArmurePhysique?: T;
  valeurBouclier?: T;
  modificateur?: T;
  valeurRupture?: T;
  mods?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  user?: T;
  nom?: T;
  sexe?: T;
  origine?: T;
  affiliation?: T;
  groupe?: T;
  pointsDeRang?: T;
  konis?: T;
  legende?: T;
  force?: T;
  habilite?: T;
  connaissances?: T;
  culture?: T;
  anticipation?: T;
  perception?: T;
  armureTete?: T;
  armureTorse?: T;
  armureBras?: T;
  armureJambes?: T;
  armePrincipale?: T;
  armeSecondaire?: T;
  armeLourde?: T;
  armeDePoing?: T;
  armeDeMelee?: T;
  backpack?: T;
  vaisseau?: T;
  roleVaisseau?: T;
  competences?:
    | T
    | {
        competence?: T;
        valeur?: T;
        id?: T;
      };
  competencesSpeciales?:
    | T
    | {
        nom?: T;
        valeur?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}