/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'lore-articles': LoreArticle;
    groups: Group;
    ships: Ship;
    'ship-models': ShipModel;
    'ship-sale-models': ShipSaleModel;
    'ship-weapons': ShipWeapon;
    'ship-modules': ShipModule;
    'ship-consumables': ShipConsumable;
    weapons: Weapon;
    armors: Armor;
    'armor-sets': ArmorSet;
    characters: Character;
    mods: Mod;
    consumables: Consumable;
    chips: Chip;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'armor-sets': {
      pieces: 'armors';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'lore-articles': LoreArticlesSelect<false> | LoreArticlesSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    ships: ShipsSelect<false> | ShipsSelect<true>;
    'ship-models': ShipModelsSelect<false> | ShipModelsSelect<true>;
    'ship-sale-models': ShipSaleModelsSelect<false> | ShipSaleModelsSelect<true>;
    'ship-weapons': ShipWeaponsSelect<false> | ShipWeaponsSelect<true>;
    'ship-modules': ShipModulesSelect<false> | ShipModulesSelect<true>;
    'ship-consumables': ShipConsumablesSelect<false> | ShipConsumablesSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    armors: ArmorsSelect<false> | ArmorsSelect<true>;
    'armor-sets': ArmorSetsSelect<false> | ArmorSetsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    mods: ModsSelect<false> | ModsSelect<true>;
    consumables: ConsumablesSelect<false> | ConsumablesSelect<true>;
    chips: ChipsSelect<false> | ChipsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Détermine les droits de l'utilisateur dans l'application.
   */
  role: 'admin' | 'player';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles encyclopédiques de l'univers Space Squad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lore-articles".
 */
export interface LoreArticle {
  id: number;
  title: string;
  /**
   * Généré automatiquement depuis le titre. Modifiable manuellement si besoin.
   */
  slug?: string | null;
  category:
    | 'chronologies'
    | 'especes-non-humaines'
    | 'politique'
    | 'technologie'
    | 'chroniques'
    | 'culture'
    | 'stardash';
  /**
   * Courte description affichée dans les listes et aperçus (facultatif).
   */
  excerpt?: string | null;
  /**
   * Image d'en-tête de l'article (facultatif).
   */
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  nom: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ships".
 */
export interface Ship {
  id: number;
  nom: string;
  modele: number | ShipModel;
  /**
   * Le personnage qui a acheté ce vaisseau.
   */
  proprietaire?: (number | null) | Character;
  blindageActuel?: number | null;
  bouclierActuel?: number | null;
  esquiveActuelle?: number | null;
  consommationActuelle?: number | null;
  pilote?: (number | null) | Character;
  copilote?: (number | null) | Character;
  /**
   * Un canonnier par tourelle disponible.
   */
  canonniers?:
    | {
        personnage?: (number | null) | Character;
        tourelle?: number | null;
        id?: string | null;
      }[]
    | null;
  moduleGenerateur?: (number | null) | ShipModule;
  modulePropulseurs?: (number | null) | ShipModule;
  moduleSurvie?: (number | null) | ShipModule;
  moduleBoucliers?: (number | null) | ShipModule;
  /**
   * Modules supplémentaires installés (limité par le nombre d'emplacements du modèle).
   */
  modulesSupplementaires?: (number | ShipModule)[] | null;
  /**
   * Armes montées sur les points d'emport du pilote.
   */
  armesPilote?: (number | ShipWeapon)[] | null;
  armesTourelles?:
    | {
        tourelle?: number | null;
        armes?: (number | ShipWeapon)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Limité par le nombre d'emplacements consommables du modèle.
   */
  consommablesVaisseau?:
    | {
        consommable: number | ShipConsumable;
        quantite: number;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-models".
 */
export interface ShipModel {
  id: number;
  nom: string;
  classe: 'alpha' | 'beta' | 'gamma' | 'delta';
  categorie: 'polyvalent' | 'combat' | 'exploration' | 'transport';
  tourelles: number;
  /**
   * Nombre d'armes équipables par le pilote.
   */
  pointsEmportPilote: number;
  /**
   * Nombre d'armes par tourelle, séparés par des +. Ex: 1+2 pour 2 tourelles.
   */
  pointsEmportTourelles?: string | null;
  blindage: number;
  /**
   * Emplacements de modules. Format: base+tourelle(s). Ex: 1+1 = 1 base + 1 tourelle.
   */
  modulesSupplementaires?: string | null;
  consommables: number;
  /**
   * Esquive de base selon la taille : Alpha=15, Beta=12, Gamma=9, Delta=6.
   */
  esquiveBase?: number | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  /**
   * Utilisateur propriétaire de ce personnage (1 personnage par compte).
   */
  user: number | User;
  nom?: string | null;
  sexe?: ('M' | 'F' | 'X') | null;
  origine?: ('Humain' | 'Strani' | 'Vada') | null;
  affiliation?: ('Alliance' | 'Union' | 'Guilde') | null;
  groupe?: (number | null) | Group;
  pointsDeRang?: number | null;
  pointsDeCompetence?: number | null;
  konis?: number | null;
  legende?: number | null;
  /**
   * Bonus fixe N ajouté aux points de blessures max. Modifiable uniquement par un admin.
   */
  bonusPointsDeBlessures?: number | null;
  reputation?:
    | {
        categorie: string;
        valeur: number;
        id?: string | null;
      }[]
    | null;
  pointsDeFaction?: number | null;
  rangDeFaction?: string | null;
  force?: number | null;
  habilite?: number | null;
  connaissances?: number | null;
  culture?: number | null;
  anticipation?: number | null;
  perception?: number | null;
  /**
   * Malus de blessures (soustraits du total). Seuls les admins peuvent les modifier.
   */
  malusForce?: number | null;
  malusHabilite?: number | null;
  malusConnaissances?: number | null;
  malusCulture?: number | null;
  malusAnticipation?: number | null;
  malusPerception?: number | null;
  armureTete?: {
    item?: (number | null) | Armor;
    mods?: (number | Mod)[] | null;
  };
  armureTorse?: {
    item?: (number | null) | Armor;
    mods?: (number | Mod)[] | null;
  };
  armureBras?: {
    item?: (number | null) | Armor;
    mods?: (number | Mod)[] | null;
  };
  armureJambes?: {
    item?: (number | null) | Armor;
    mods?: (number | Mod)[] | null;
  };
  armureBackpack?: {
    item?: (number | null) | Armor;
  };
  armePrincipale?: {
    item?: (number | null) | Weapon;
    mods?: (number | Mod)[] | null;
  };
  armeSecondaire?: {
    item?: (number | null) | Weapon;
    mods?: (number | Mod)[] | null;
  };
  armeLourde?: {
    item?: (number | null) | Weapon;
    mods?: (number | Mod)[] | null;
  };
  armeDeMelee?: {
    item?: (number | null) | Weapon;
    mods?: (number | Mod)[] | null;
  };
  consommableEquipe1?: (number | null) | Consumable;
  consommableEquipe2?: (number | null) | Consumable;
  consommableEquipe3?: (number | null) | Consumable;
  puceMk1?: (number | null) | Chip;
  puceMk2?: (number | null) | Chip;
  puceMk3?: (number | null) | Chip;
  vaisseau?: (number | null) | Ship;
  roleVaisseau?: ('pilote' | 'copilote' | 'canonnier' | 'passager') | null;
  inventaireArmes?:
    | {
        item: number | Weapon;
        mods?: (number | Mod)[] | null;
        id?: string | null;
      }[]
    | null;
  inventaireArmures?:
    | {
        item: number | Armor;
        mods?: (number | Mod)[] | null;
        id?: string | null;
      }[]
    | null;
  inventaireMods?: (number | Mod)[] | null;
  inventairePuces?: (number | Chip)[] | null;
  /**
   * Liste des consommables possédés par le personnage.
   */
  inventaire?:
    | {
        consommable: number | Consumable;
        quantite: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Compétences de la liste standard et leur niveau.
   */
  competences?:
    | {
        competence:
          | 'Chasseur'
          | 'Bombardier'
          | 'Poids Lourds'
          | 'Transport de Troupes'
          | 'Canonnier'
          | 'Médecine de terrain'
          | 'Concentration'
          | 'Mécanicien'
          | 'Stabilisation'
          | 'Assaut'
          | 'Sniper'
          | 'Shotgun'
          | 'Combat rapproché'
          | 'Analyse'
          | 'Réactivité'
          | 'Furtivité'
          | 'Diplomate'
          | 'Culture';
        valeur: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Compétences uniques, hors liste standard, propres à ce personnage.
   */
  competencesSpeciales?:
    | {
        nom: string;
        valeur: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armors".
 */
export interface Armor {
  id: number;
  nom: string;
  categorie: 'tete' | 'torse' | 'bras' | 'jambes' | 'backpack';
  valeurArmurePhysique?: number | null;
  valeurBouclier?: number | null;
  valeurRupture?: number | null;
  /**
   * Si vide, égal à l'armure physique.
   */
  poids?: number | null;
  /**
   * Champ texte pour les modificateurs divers.
   */
  modificateur?: string | null;
  prix?: number | null;
  /**
   * Capacité de stockage (uniquement pour les back-packs).
   */
  stockage?: number | null;
  image?: (number | null) | Media;
  /**
   * Set auquel appartient cette pièce d'armure.
   */
  set?: (number | null) | ArmorSet;
  /**
   * ATTENTION : Ce champ est conservé pour la compatibilité mais les mods doivent être gérés au niveau du personnage.
   */
  mods?: (number | Mod)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armor-sets".
 */
export interface ArmorSet {
  id: number;
  nom: string;
  /**
   * Bonus appliqué lorsque le set est complet.
   */
  bonus: string;
  image?: (number | null) | Media;
  /**
   * Liste des pièces d'armure appartenant à ce set.
   */
  pieces?: {
    docs?: (number | Armor)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mods".
 */
export interface Mod {
  id: number;
  nom: string;
  categoriePrincipale: 'armes' | 'armures';
  /**
   * Pour une arme, le prix est un pourcentage du prix de l'arme (ex: 0.10 pour 10%). Pour une armure, c'est un prix fixe.
   */
  prix?: number | null;
  sousCategorieArme?: ('toutes' | 'fusils-pistolets' | 'shotgun' | 'snipers' | 'melee') | null;
  sousCategorieArmure?: ('toutes' | 'tete' | 'torse' | 'bras' | 'jambes') | null;
  effet: string;
  modificateurs?:
    | {
        cible:
          | 'stat_force'
          | 'stat_habilite'
          | 'stat_connaissances'
          | 'stat_culture'
          | 'stat_anticipation'
          | 'stat_perception'
          | 'armure_physique'
          | 'armure_bouclier'
          | 'armure_rupture'
          | 'degats_flat'
          | 'degats_mod_fo_x1'
          | 'degats_mod_pe_x1'
          | 'portee_courte'
          | 'portee_moyenne'
          | 'mod_portee_courte'
          | 'mod_portee_moyenne'
          | 'chargeur'
          | 'chargeur_pct'
          | 'poids'
          | 'refroidissement_pct'
          | 'indicator_surcharge'
          | 'indicator_projectiles'
          | 'indicator_acide'
          | 'indicator_tazer'
          | 'indicator_gravite_faible'
          | 'indicator_gravite_forte'
          | 'indicator_lumiere'
          | 'indicator_double_pistolet'
          | 'epreuve_pilotage_leger'
          | 'epreuve_pilotage_intermediaire'
          | 'epreuve_pilotage_lourd'
          | 'epreuve_pilotage_blinde'
          | 'epreuve_tir_pilote'
          | 'epreuve_tir_tourelle'
          | 'epreuve_tir_vehicule'
          | 'epreuve_reparation'
          | 'epreuve_negocier'
          | 'epreuve_analyse'
          | 'epreuve_culture'
          | 'epreuve_discretion'
          | 'epreuve_initiative'
          | 'epreuve_tir_assaut'
          | 'epreuve_tir_sniper'
          | 'epreuve_tir_shotgun'
          | 'epreuve_cac'
          | 'epreuve_soins';
        valeur: number;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: number;
  nom: string;
  fabricant?: string | null;
  categorie: 'fusil-assaut' | 'shotgun' | 'sniper' | 'pistolet' | 'melee' | 'lourde';
  type: ('thermique' | 'cinetique' | 'plasma' | 'explosif' | 'melee')[];
  /**
   * Format: [nombre de dés]d[taille du dé]
   */
  valeurDegats?: string | null;
  poids?: number | null;
  prix?: number | null;
  /**
   * Pour la mélée, correspond à la taille de la lame. Pour les armes lourdes, il s'agit de la portée maximale fixe.
   */
  porteeFixe?: number | null;
  projectilesParTir?: number | null;
  valeurChauffe?: number | null;
  /**
   * Distance maximale pour le premier palier.
   */
  courtePortee?: number | null;
  modCourtePortee?: number | null;
  /**
   * Distance maximale pour le second palier.
   */
  moyennePortee?: number | null;
  modMoyennePortee?: number | null;
  /**
   * Définissez les 3 paliers de distance (le 1er étant déjà la courte portée au-dessus).
   */
  paliersSniper?:
    | {
        distanceMax: number;
        modificateur: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Distance additionnelle après le dernier palier provoquant un malus cumulatif.
   */
  trancheMalusLonguePortee?: number | null;
  malusParTranche?: number | null;
  /**
   * Pour les armes plasma, correspond à la taille du conteneur.
   */
  tailleChargeur?: number | null;
  tempsRechargement?: number | null;
  zoneEffet?: string | null;
  /**
   * Pourcentage de refroidissement par unité de temps.
   */
  tempsRefroidissement?: number | null;
  details?: string | null;
  image?: (number | null) | Media;
  /**
   * ATTENTION : Ce champ est conservé pour la compatibilité mais les mods doivent être gérés au niveau du personnage.
   */
  mods?: (number | Mod)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consumables".
 */
export interface Consumable {
  id: number;
  nom: string;
  categorie: 'soins' | 'munitions' | 'grenades' | 'tactique' | 'outils';
  /**
   * Texte libre décrivant l'effet du consommable.
   */
  effet?: string | null;
  /**
   * Texte libre décrivant l'épreuve éventuelle (ex: Physique, Habilité).
   */
  epreuve?: string | null;
  /**
   * Valeur numérique du modificateur (ex: -10, +5).
   */
  modificateurEpreuve?: number | null;
  prix?: number | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chips".
 */
export interface Chip {
  id: number;
  nom: string;
  categorie: 'active' | 'passive';
  effet: string;
  restriction?: string | null;
  cooldown?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-modules".
 */
export interface ShipModule {
  id: number;
  nom: string;
  famille:
    | '_base_header'
    | 'generateur'
    | 'propulseurs'
    | 'survie'
    | 'boucliers'
    | '_supp_header'
    | 'blindage'
    | 'reparateur'
    | 'hangar'
    | 'scanner'
    | 'infirmerie'
    | 'sas-abordage'
    | 'ordinateur-tir'
    | 'harmonisateur'
    | 'baie-amarrage'
    | 'pilotage-assiste'
    | 'propulseurs-stardash';
  typeModule: 'base' | 'supplementaire';
  taille: '1' | '2' | '3' | '4';
  modele: 'E' | 'D' | 'C' | 'B' | 'A' | 'S';
  consommation?: number | null;
  prix?: string | null;
  /**
   * Puissance du générateur (ex: 6 GW).
   */
  puissance?: string | null;
  /**
   * Bonus apportés (ex: Esquive +3, Tir(pilote)+2, Crypto +1, Dash +1).
   */
  modificateurs?: string | null;
  bouclierMax?: number | null;
  /**
   * Nombre de tours avant réactivation.
   */
  cooldownBouclier?: number | null;
  rechargeBouclier?: number | null;
  /**
   * Réparations par tour (max). Ex: 3 (12).
   */
  reparations?: string | null;
  malusPoids?: number | null;
  blindageBonus?: number | null;
  /**
   * Capacité ou nombre de places.
   */
  capacite?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-weapons".
 */
export interface ShipWeapon {
  id: number;
  nom: string;
  taille: '1' | '2' | '3' | '4';
  modele: 'G' | 'F' | 'E' | 'D' | 'C' | 'B' | 'A' | 'S';
  type: 'thermique' | 'cinetique' | 'explosif' | 'blindage';
  categorie?: ('cartouche' | 'cinetique' | 'lance-missile' | 'mine' | 'bouclier-joute') | null;
  degats?: string | null;
  moyenne?: number | null;
  chauffe?: number | null;
  ballesParSalve?: number | null;
  chargeur?: number | null;
  distance?: string | null;
  cooldown?: number | null;
  bonusBlindage?: number | null;
  /**
   * Nombre de points d'emport consommés (ex: x2 pour lance-missiles).
   */
  pointsEmport?: number | null;
  /**
   * Prix de l'arme (ex: 100 k, 1 M).
   */
  prix?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-consumables".
 */
export interface ShipConsumable {
  id: number;
  nom: string;
  categorie?: ('munitions' | 'cartouches' | 'roquettes' | 'mines' | 'reparation' | 'energie' | 'autre') | null;
  taille?: ('toutes' | '1' | '2' | '3' | '4') | null;
  modele?: ('G' | 'F' | 'E' | 'D' | 'C' | 'B' | 'A' | 'S') | null;
  /**
   * Calibre ou capacité (ex: 1200 MJ, 50mm).
   */
  calibre?: string | null;
  /**
   * Bonus apporté (ex: Dgts+4, Tir +2, Refroidissement).
   */
  bonus?: string | null;
  prix?: string | null;
  effet?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-sale-models".
 */
export interface ShipSaleModel {
  id: number;
  nom: string;
  /**
   * Le châssis de base sur lequel ce modèle est construit.
   */
  chassis: number | ShipModel;
  /**
   * Prix du modèle complet (ex: 100 k, 1 M, 1,25 M).
   */
  prix?: string | null;
  generateur: number | ShipModule;
  propulseurs: number | ShipModule;
  boucliers: number | ShipModule;
  survie: number | ShipModule;
  armes?:
    | {
        arme: number | ShipWeapon;
        emplacement?: ('pilote' | 'tourelle-1' | 'tourelle-2' | 'tourelle-3' | 'tourelle-4') | null;
        id?: string | null;
      }[]
    | null;
  modulesOptionnels?: (number | ShipModule)[] | null;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'lore-articles';
        value: number | LoreArticle;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'ships';
        value: number | Ship;
      } | null)
    | ({
        relationTo: 'ship-models';
        value: number | ShipModel;
      } | null)
    | ({
        relationTo: 'ship-sale-models';
        value: number | ShipSaleModel;
      } | null)
    | ({
        relationTo: 'ship-weapons';
        value: number | ShipWeapon;
      } | null)
    | ({
        relationTo: 'ship-modules';
        value: number | ShipModule;
      } | null)
    | ({
        relationTo: 'ship-consumables';
        value: number | ShipConsumable;
      } | null)
    | ({
        relationTo: 'weapons';
        value: number | Weapon;
      } | null)
    | ({
        relationTo: 'armors';
        value: number | Armor;
      } | null)
    | ({
        relationTo: 'armor-sets';
        value: number | ArmorSet;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'mods';
        value: number | Mod;
      } | null)
    | ({
        relationTo: 'consumables';
        value: number | Consumable;
      } | null)
    | ({
        relationTo: 'chips';
        value: number | Chip;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lore-articles_select".
 */
export interface LoreArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  nom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ships_select".
 */
export interface ShipsSelect<T extends boolean = true> {
  nom?: T;
  modele?: T;
  proprietaire?: T;
  blindageActuel?: T;
  bouclierActuel?: T;
  esquiveActuelle?: T;
  consommationActuelle?: T;
  pilote?: T;
  copilote?: T;
  canonniers?:
    | T
    | {
        personnage?: T;
        tourelle?: T;
        id?: T;
      };
  moduleGenerateur?: T;
  modulePropulseurs?: T;
  moduleSurvie?: T;
  moduleBoucliers?: T;
  modulesSupplementaires?: T;
  armesPilote?: T;
  armesTourelles?:
    | T
    | {
        tourelle?: T;
        armes?: T;
        id?: T;
      };
  consommablesVaisseau?:
    | T
    | {
        consommable?: T;
        quantite?: T;
        id?: T;
      };
  notes?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-models_select".
 */
export interface ShipModelsSelect<T extends boolean = true> {
  nom?: T;
  classe?: T;
  categorie?: T;
  tourelles?: T;
  pointsEmportPilote?: T;
  pointsEmportTourelles?: T;
  blindage?: T;
  modulesSupplementaires?: T;
  consommables?: T;
  esquiveBase?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-sale-models_select".
 */
export interface ShipSaleModelsSelect<T extends boolean = true> {
  nom?: T;
  chassis?: T;
  prix?: T;
  generateur?: T;
  propulseurs?: T;
  boucliers?: T;
  survie?: T;
  armes?:
    | T
    | {
        arme?: T;
        emplacement?: T;
        id?: T;
      };
  modulesOptionnels?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-weapons_select".
 */
export interface ShipWeaponsSelect<T extends boolean = true> {
  nom?: T;
  taille?: T;
  modele?: T;
  type?: T;
  categorie?: T;
  degats?: T;
  moyenne?: T;
  chauffe?: T;
  ballesParSalve?: T;
  chargeur?: T;
  distance?: T;
  cooldown?: T;
  bonusBlindage?: T;
  pointsEmport?: T;
  prix?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-modules_select".
 */
export interface ShipModulesSelect<T extends boolean = true> {
  nom?: T;
  famille?: T;
  typeModule?: T;
  taille?: T;
  modele?: T;
  consommation?: T;
  prix?: T;
  puissance?: T;
  modificateurs?: T;
  bouclierMax?: T;
  cooldownBouclier?: T;
  rechargeBouclier?: T;
  reparations?: T;
  malusPoids?: T;
  blindageBonus?: T;
  capacite?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ship-consumables_select".
 */
export interface ShipConsumablesSelect<T extends boolean = true> {
  nom?: T;
  categorie?: T;
  taille?: T;
  modele?: T;
  calibre?: T;
  bonus?: T;
  prix?: T;
  effet?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  nom?: T;
  fabricant?: T;
  categorie?: T;
  type?: T;
  valeurDegats?: T;
  poids?: T;
  prix?: T;
  porteeFixe?: T;
  projectilesParTir?: T;
  valeurChauffe?: T;
  courtePortee?: T;
  modCourtePortee?: T;
  moyennePortee?: T;
  modMoyennePortee?: T;
  paliersSniper?:
    | T
    | {
        distanceMax?: T;
        modificateur?: T;
        id?: T;
      };
  trancheMalusLonguePortee?: T;
  malusParTranche?: T;
  tailleChargeur?: T;
  tempsRechargement?: T;
  zoneEffet?: T;
  tempsRefroidissement?: T;
  details?: T;
  image?: T;
  mods?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armors_select".
 */
export interface ArmorsSelect<T extends boolean = true> {
  nom?: T;
  categorie?: T;
  valeurArmurePhysique?: T;
  valeurBouclier?: T;
  valeurRupture?: T;
  poids?: T;
  modificateur?: T;
  prix?: T;
  stockage?: T;
  image?: T;
  set?: T;
  mods?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "armor-sets_select".
 */
export interface ArmorSetsSelect<T extends boolean = true> {
  nom?: T;
  bonus?: T;
  image?: T;
  pieces?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  user?: T;
  nom?: T;
  sexe?: T;
  origine?: T;
  affiliation?: T;
  groupe?: T;
  pointsDeRang?: T;
  pointsDeCompetence?: T;
  konis?: T;
  legende?: T;
  bonusPointsDeBlessures?: T;
  reputation?:
    | T
    | {
        categorie?: T;
        valeur?: T;
        id?: T;
      };
  pointsDeFaction?: T;
  rangDeFaction?: T;
  force?: T;
  habilite?: T;
  connaissances?: T;
  culture?: T;
  anticipation?: T;
  perception?: T;
  malusForce?: T;
  malusHabilite?: T;
  malusConnaissances?: T;
  malusCulture?: T;
  malusAnticipation?: T;
  malusPerception?: T;
  armureTete?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armureTorse?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armureBras?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armureJambes?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armureBackpack?:
    | T
    | {
        item?: T;
      };
  armePrincipale?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armeSecondaire?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armeLourde?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  armeDeMelee?:
    | T
    | {
        item?: T;
        mods?: T;
      };
  consommableEquipe1?: T;
  consommableEquipe2?: T;
  consommableEquipe3?: T;
  puceMk1?: T;
  puceMk2?: T;
  puceMk3?: T;
  vaisseau?: T;
  roleVaisseau?: T;
  inventaireArmes?:
    | T
    | {
        item?: T;
        mods?: T;
        id?: T;
      };
  inventaireArmures?:
    | T
    | {
        item?: T;
        mods?: T;
        id?: T;
      };
  inventaireMods?: T;
  inventairePuces?: T;
  inventaire?:
    | T
    | {
        consommable?: T;
        quantite?: T;
        id?: T;
      };
  competences?:
    | T
    | {
        competence?: T;
        valeur?: T;
        id?: T;
      };
  competencesSpeciales?:
    | T
    | {
        nom?: T;
        valeur?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mods_select".
 */
export interface ModsSelect<T extends boolean = true> {
  nom?: T;
  categoriePrincipale?: T;
  prix?: T;
  sousCategorieArme?: T;
  sousCategorieArmure?: T;
  effet?: T;
  modificateurs?:
    | T
    | {
        cible?: T;
        valeur?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consumables_select".
 */
export interface ConsumablesSelect<T extends boolean = true> {
  nom?: T;
  categorie?: T;
  effet?: T;
  epreuve?: T;
  modificateurEpreuve?: T;
  prix?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chips_select".
 */
export interface ChipsSelect<T extends boolean = true> {
  nom?: T;
  categorie?: T;
  effet?: T;
  restriction?: T;
  cooldown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}